name: 'Hugo Action'
description: 'Build hugo site, deploy to github page'
branding:
  icon: 'award'  
  color: 'green'
inputs:
  branch: # id of input
    description: 'which branch will publish'
    required: true
    default: 'master'
outputs:
  time:
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'wxdlong/hugo'
  args:
    - ${{ inputs.who-to-greet }}