name: 'Hugo in Action'
description: 'Build hugo site, deploy to github page'
branding:
  icon: 'award'  
  color: 'green'
inputs:
  branch: # id of input
    description: 'which branch will publish'
    required: true
    default: 'master'
runs:
  using: 'docker'
  image: 'wxdlong/hugo'