name: 'Hugo in Action'
description: 'Build Hugo extended site, Deploy to GitHub Page'
branding:
  icon: 'aperture'  
  color: 'red'


inputs:
  access_token:
    description: 'Github access token,'
    required: true
  branch: # id of input
    description: 'Which branch will publish. Default value is gh-pages for unit|organization, If for personal set value to master'
    required: false
    default: 'gh-pages'
  cname:
    description: 'Github page cname. eg: https://ycat.top'
    required: false
    default: ''

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.access_token }}
    - ${{ inputs.branch }}
    - ${{ inputs.cname }}